language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./script/cibuild.sh

script: ./cibuild.sh

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer