language: ruby
rvm:
- 2.1

before_script:
 - bundle install

script: rake test

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer